### Obtener todas las tracks (GET)
GET http://localhost:3000/tracks
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2M4MzQxZWFkNWZhYWE5MjQ1OWQzMDkiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQxMjUwMDI4LCJleHAiOjE3NDEyNTcyMjh9.fF8FS5EXXuyYBdL_Y1-Sw-TQie-dnhKPV7QUlP3Pcvo

###

### Crear una nueva track (POST)
POST http://localhost:3000/tracks
Content-Type: application/json
api_key: Api-publica-123
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2M4MzQxZWFkNWZhYWE5MjQ1OWQzMDkiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQxMjUwMDI4LCJleHAiOjE3NDEyNTcyMjh9.fF8FS5EXXuyYBdL_Y1-Sw-TQie-dnhKPV7QUlP3Pcvo

{
  "artist": {
    "name": "Juan Perez",
    "nickname": "JP",
    "edad": 35
  },
  "album": "Mi primer álbum",
  "cover": "http://ejemplo.com/cover.jpg"
}
### Actualizar un track (PUT)
PUT http://localhost:3000/tracks/67adb9d213060a8b08f40c7c
Content-Type: application/json

{
  "artist": {
    "name": "Nuevo nombre",
    "nickname": "Nuevo apodo",
    "edad": 40
  },
  "album": "Nuevo álbum",
  "cover": "http://ejemplo.com/nuevo-cover.jpg"
}
###

### DELETE
DELETE http://localhost:3000/tracks/67c823e9bb861933bb4eeb80
Content-Type: application/json

### IMagen
POST http://localhost:3000/storage HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="image"; filename="bici_lago.jpeg"
Content-Type: image/jpeg

< ./bici_lago.jpeg
--boundary123--


###
GET http://localhost:3000/tracks
Accept: application/json

###
GET http://localhost:3000/users/67c8341ead5faaa92459d309
Accept: application/json


###
POST http://localhost:3000/users
Content-Type: application/json
api_key: Api-publica-123

{
  "name": "Sergio Mahía",
  "age": 28,
  "email": "sergio.mahiarello@gmail.com",
  "password": "password123",
  "role": "user"
}

###PUT
PUT http://localhost:3000/users/67c8341ead5faaa92459d309
api_key: Api-publica-123
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2M4MzQxZWFkNWZhYWE5MjQ1OWQzMDkiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQxMjUwMDI4LCJleHAiOjE3NDEyNTcyMjh9.fF8FS5EXXuyYBdL_Y1-Sw-TQie-dnhKPV7QUlP3Pcvo
Content-Type: application/json

{
  "name": "Carlos López Updated",
  "age": 29,
  "email": "carlos_updated@example.com",
  "role": "admin"
}

###DELETE
DELETE http://localhost:3000/users/67c02d6770ad59611c284638
Content-Type: application/json

###POST REGISTER
POST http://localhost:3000/auth/register
Content-Type: application/json
api_key: Api-publica-123

{
  "name": "Sergio Mahía",
  "age": 28,
  "email": "sergio.mahiarello@gmail.com",
  "password": "password123",
  "role": "user"
}

###POST LOGIN
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "sergio.mahiarello@gmail.com",
  "password": "password123"
}



